### ISSUE TITLE
Version 0.1 - Task List 

### ISSUE THREAD

**Issue by hieubui149** [hieubui149/wallet-buddy#2]
# Task List
## Layout components
- [ ] Header
- [ ] Footer
- [ ] Profile/user dropdown

## Wallet common pages
- [ ] Wallet Buddy welcome page
- [ ] Wallet detail page for Crypto wallet
- [ ] Wallet detail page for Bank wallet

## Wallet Crypto in detail
- [ ] [Crypto Wallet] CRUD transactions
- [ ] [Crypto Wallet] Present transactions as charts (chart by token, chart by profit/loss, total asset, ...)
- [ ] [Crypto Wallet] AI prediction?
- [ ] [Crypto Wallet] CSV Import.

## Wallet Bank in detail
- [ ] [Bank Wallet] CRUD transactions
- [ ] [Bank Wallet] Balance view

**Comment by hieubui149** [comment]
I'll work on the "Wallet detail page for Crypto wallet"
